kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/version: 0.19.0
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]