apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/version: 0.19.0
  name: snmp-exporter
  namespace: monitoring