apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/version: 0.19.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: snmp-exporter
      app.kubernetes.io/part-of: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/name: snmp-exporter
        app.kubernetes.io/version: 0.19.0
    spec:
      restartPolicy: Always
      serviceAccountName: snmp-exporter
      containers:
        - name: snmp-exporter
          image: "prom/snmp-exporter:v0.19.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 9116
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
      volumes: