apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-backend-icmp
  namespace: monitoring
spec:
  jobName: icmp-ipv4
  interval: 60s
  module: icmp_ipv4
  prober:
    url: blackbox-exporter.monitoring.svc:19115
    scheme: icmp_ipv4
    path: /probe
  targets:
    staticConfig:
      static:
      - python-guestbook-frontend.default.svc
