apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: python-guestbook-backend
  labels:
    app: python-guestbook
    tier: backend
spec:
  selector:
    matchLabels:
      app: python-guestbook
      tier: backend
  podMetricsEndpoints:
  - interval: 15s
    port: http-server
    path: /metrics