apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-frontend
  namespace: monitoring
spec:
  jobName: http-get
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc:19115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - http://python-guestbook-frontend.monitoring.svc:80
